# Generated by Django 5.2.12 on 2026-10-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='free', max_length=20)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
