# Generated by Django 5.2.12 on 2026-10-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('market', models.CharField(max_length=100)),
                ('minimum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('is_sample', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
