# Generated by Django 5.2.12 on 2026-10-06 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('district', models.CharField(choices=[('Lucknow', 'Lucknow'), ('Rae Bareli', 'Rae Bareli'), ('Gorakhpur', 'Gorakhpur'), ('Varanasi', 'Varanasi')], max_length=30)),
                ('village', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English')], default='hi', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
