import {useEffect,useState} from 'react';
import {Sprout,LayoutDashboard,MessageCircle,Camera,CloudSun,ChartNoAxesCombined,Leaf,Headphones,ShieldCheck,ArrowLeft,Bell,ChevronDown,Menu,X} from 'lucide-react';
import Home,{type Page} from './Home';
import Auth from './Auth';
import Chat from './Chat';
import Doctor from './Doctor';
import {Weather,Market} from './DataPages';
import Farm from './Farm';
import Expert from './Expert';
import Admin from './Admin';
import {api,ApiError,hasToken,setToken} from './api';
import {labels,type Language} from './i18n';
export default function App(){
 const [lang,setLang]=useState<Language>((localStorage.getItem('agri-language') as Language)==='en'?'en':'hi');const [page,setPage]=useState<Page>('home');const [district,setDistrict]=useState('Lucknow');const [profile,setProfile]=useState<any>(null);const [auth,setAuth]=useState(false);const [loggedIn,setLoggedIn]=useState(hasToken());const [staff,setStaff]=useState(false);const [initial,setInitial]=useState('');const [mobileMenu,setMobileMenu]=useState(false);const [notify,setNotify]=useState(false);const [sessionError,setSessionError]=useState('');const t=labels[lang];
 async function loadProfile(){if(!hasToken())return;setSessionError('');try{const d=await api('farmers/me');setProfile(d.profile);setDistrict(d.profile.district);setLang(d.profile.language);setLoggedIn(true);setStaff(false);}catch(error){if(error instanceof ApiError && error.status===404){try{await api('admin/analytics');setStaff(true);setLoggedIn(true);setProfile(null);return;}catch(adminError){error=adminError;}}if(error instanceof ApiError && error.status===401){setToken('');setLoggedIn(false);setStaff(false);setProfile(null);setSessionError('सत्र समाप्त हो गया है। कृपया फिर से लॉग इन करें।');return;}setLoggedIn(true);setSessionError(error instanceof ApiError && error.status===403?'इस खाते को यह जानकारी देखने की अनुमति नहीं है।':'सर्वर या इंटरनेट अभी उपलब्ध नहीं है। आपका लॉग इन सुरक्षित है। थोड़ी देर बाद फिर प्रयास करें।');}}
 useEffect(()=>{loadProfile()},[]);useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('agri-language',lang)},[lang]);
 function go(p:Page){setMobileMenu(false);if(p!=='home'&&!loggedIn){setPage(p);setAuth(true);return}setPage(p);window.scrollTo({top:0,behavior:'smooth'})}
 async function changeLanguage(value:Language){setLang(value);if(loggedIn&&!staff){try{await api('farmers/me',{method:'PATCH',body:JSON.stringify({language:value})});}catch{setSessionError('भाषा की पसंद सहेज नहीं सके। फिर से प्रयास करें।')}}}
 async function logout(){try{await api('auth/logout',{method:'POST'})}catch{}setToken('');setProfile(null);setLoggedIn(false);setStaff(false);setPage('home')}
 const navigation:[Page,typeof Leaf][]=[['home',LayoutDashboard],['ask',MessageCircle],['doctor',Camera],['weather',CloudSun],['market',ChartNoAxesCombined],['farm',Leaf]];
 return <div className="app-shell"><aside className={`sidebar ${mobileMenu?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('home')}}><span className="brand-mark"><Sprout size={29}/></span><div><strong>Shivam <span>Agri AI</span></strong><small>{lang==='hi'?'आपकी खेती का साथी':'Your farming companion'}</small></div></a><button className="mobile-close" onClick={()=>setMobileMenu(false)} aria-label="Close menu"><X/></button><div className="nav-caption">{lang==='hi'?'आपकी खेती':'YOUR WORKSPACE'}</div><nav>{navigation.map(([p,Icon])=><button key={p} className={page===p?'active':''} onClick={()=>go(p)}><Icon size={21}/>{t[p]}{p==='ask'&&<span className="ai-pill">AI</span>}</button>)}</nav><div className="nav-divider"/><nav><button className={page==='expert'?'active':''} onClick={()=>go('expert')}><Headphones size={21}/>{t.expert}</button>{staff&&<button className={page==='admin'?'active':''} onClick={()=>go('admin')}><ShieldCheck size={21}/>{t.admin}</button>}</nav><div className="sidebar-tip"><span>🌱</span><h4>{lang==='hi'?'हर कदम पर साथ':'Growing together'}</h4><p>{lang==='hi'?'छोटे सवाल से शुरू करें। बेहतर खेती की ओर बढ़ें।':'Start with a question. Grow with better guidance.'}</p><button onClick={()=>go('ask')}>{lang==='hi'?'AI से बात करें':'Talk to AI'} →</button></div><div className="sidebar-footer"><span className="status-dot"/> {lang==='hi'?'उत्तर प्रदेश पायलट':'UTTAR PRADESH PILOT'}<small>© 2026 Shivam Agri AI</small></div></aside>
 <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="mobile-menu" onClick={()=>setMobileMenu(true)} aria-label="Open menu"><Menu/></button><span>{lang==='hi'?'किसान सहायता केंद्र':'Farmer assistance center'}</span><span className="beta">PILOT</span></div><div className="topbar-actions"><div className="language-select"><span>अ / A</span><select aria-label="Language" value={lang} onChange={e=>changeLanguage(e.target.value as Language)}><option value="hi">हिंदी</option><option value="en">English</option></select></div><button className="notification-button" onClick={()=>setNotify(!notify)} aria-label="Notifications"><Bell size={20}/><i/></button>{loggedIn?<button className="user-button" onClick={logout}><span>{profile?.name?.[0]||'A'}</span><strong>{profile?.name||'Admin'}</strong><small>{t.logout}</small></button>:<button className="login-button" onClick={()=>setAuth(true)}>{t.login} <ChevronDown size={15}/></button>}</div></header>
 {notify&&<div className="notification-popover">कोई सत्यापित मौसम अलर्ट उपलब्ध नहीं है।</div>}<main>{sessionError&&<p className="error">{sessionError}</p>}{page==='home'?<Home lang={lang} district={district} setDistrict={setDistrict} go={go} name={profile?.name} onVoice={s=>{setInitial(s);go('ask')}}/>:<><div className="page-heading"><button className="back-button" onClick={()=>go('home')} aria-label="Back to home"><ArrowLeft size={20}/></button><div><p className="eyebrow">SHIVAM AGRI AI</p><h1>{t[page]}</h1></div></div>{!loggedIn?<section className="panel empty"><Sprout size={45}/><h2>अपनी खेती के लिए शुरू करें</h2><p>यह सुविधा उपयोग करने के लिए पंजीकरण करें या लॉग इन करें।</p><button className="primary" onClick={()=>setAuth(true)}>लॉग इन / पंजीकरण</button></section>:page==='ask'?<Chat lang={lang} initial={initial} clearInitial={()=>setInitial('')}/>:page==='doctor'?<Doctor lang={lang}/>:page==='weather'?<Weather lang={lang} district={district} setDistrict={setDistrict}/>:page==='market'?<Market lang={lang} district={district} setDistrict={setDistrict}/>:page==='farm'?<Farm lang={lang} onUpdate={loadProfile}/>:page==='expert'?<Expert lang={lang} staff={staff}/>:<Admin/>}</>}
 <footer className="main-footer"><span>Shivam Agri AI</span><span>{lang==='hi'?'किसान की समझ, तकनीक का साथ।':'Farmer wisdom, supported by technology.'}</span><span>Made for India ♡</span></footer></main></div>
 <nav className="bottom-nav">{navigation.filter(([p])=>p!=='doctor').map(([p,Icon])=><button key={p} onClick={()=>go(p)} className={p===page?'active':''}><Icon size={21}/><span>{t[p]}</span></button>)}</nav>{auth&&<Auth lang={lang} onClose={()=>setAuth(false)} onDone={()=>{setAuth(false);setSessionError('');loadProfile()}}/>}</div>
}
