import {useEffect,useRef,useState} from 'react';
import {Send,Sparkles,ThumbsUp,ThumbsDown} from 'lucide-react';
import {post} from './api';
import {VoiceButton,Speak,Notice,Safety} from './components';
import {type Language} from './i18n';
type Answer={question:string;answer:string;message_id:number;category:string;expert_required:boolean;is_demo:boolean;disclaimer:string};
export default function Chat({lang,initial='',clearInitial}:{lang:Language;initial?:string;clearInitial:()=>void}){
 const [question,setQuestion]=useState(initial);const [answers,setAnswers]=useState<Answer[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [feedback,setFeedback]=useState<Record<number,string>>({});const [comments,setComments]=useState<Record<number,string>>({});const end=useRef<HTMLDivElement>(null);const hi=lang==='hi';
 useEffect(()=>{setQuestion(initial);clearInitial()},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[answers]);
 async function ask(e:React.FormEvent){e.preventDefault();if(!question.trim())return;setBusy(true);setError('');try{const result=await post('advisory/ask',{question});setAnswers([...answers,{...result,question}]);setQuestion('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function vote(id:number,helpful:boolean,comment=''){try{await post('feedback',{message_id:id,helpful,comment});setFeedback({...feedback,[id]:helpful?'yes':'no'});}catch(e){setError((e as Error).message)}}
 async function escalate(a:Answer){try{await post('expert-cases',{question:a.question,ai_suggestion:a.answer});setFeedback({...feedback,[a.message_id]:'expert'});}catch(e){setError((e as Error).message)}}
 return <section className="panel chat-panel"><Notice>{hi?'Demo AI: सामान्य जानकारी। कोई live LLM जुड़ा नहीं है।':'Demo AI: educational guidance; no live LLM configured.'}</Notice><div className="chat-messages">{!answers.length&&<div className="chat-empty"><span className="action-icon green"><Sparkles size={30}/></span><h2>{hi?'आपकी खेती का सवाल क्या है?':'What would you like to know?'}</h2><p>{hi?'फसल, मिट्टी या खेती की योजना के बारे में पूछें।':'Ask about crops, soil or your farm plan.'}</p><div className="suggestions">{(hi?['गेहूँ के पत्ते पीले हो रहे हैं','इस मौसम में कौन सी फसल उगाऊँ?','कल बारिश होगी?','गेहूँ का मंडी भाव क्या है?']:['My wheat leaves are yellow','Which crop should I grow?','Will it rain tomorrow?','What is the wheat market price?']).map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}</button>)}</div></div>}{answers.map(a=><div key={a.message_id} className="exchange"><div className="question-bubble">{a.question}</div><div className="answer-bubble"><span className="eyebrow">{a.expert_required?'विशेषज्ञ की सलाह आवश्यक':'सामान्य शैक्षिक जानकारी'} · DEMO</span><p>{a.answer}</p><Speak text={a.answer} lang={lang}/><div className="answer-feedback"><span>{hi?'क्या यह मददगार था?':'Was this helpful?'}</span><button onClick={()=>vote(a.message_id,true)} aria-label="Helpful"><ThumbsUp size={17}/>{hi?'हाँ':'Yes'}</button><button onClick={()=>vote(a.message_id,false)} aria-label="Not helpful"><ThumbsDown size={17}/>{hi?'नहीं':'No'}</button>{feedback[a.message_id]&&<span className="success">{feedback[a.message_id]==='expert'?'विशेषज्ञ को भेज दिया गया':'धन्यवाद, feedback सहेजा गया'}</span>}</div>{feedback[a.message_id]==='no'&&<div className="inline-form"><input placeholder="क्या गलत था? (वैकल्पिक)" value={comments[a.message_id]||''} onChange={e=>setComments({...comments,[a.message_id]:e.target.value})}/><button onClick={()=>vote(a.message_id,false,comments[a.message_id])}>सहेजें</button></div>}<button className="text-button" onClick={()=>escalate(a)}>{hi?'कृषि विशेषज्ञ से पूछें':'Ask an agriculture expert'} →</button></div></div>)}<div ref={end}/></div>{error&&<p role="alert" className="error">{error}</p>}<form className="chat-form" onSubmit={ask}><textarea maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={hi?'अपना सवाल यहाँ लिखें…':'Write your question…'} aria-label="Question"/><button className="primary" disabled={busy||!question.trim()}><Send size={19}/>{busy?'…':hi?'पूछें':'Ask'}</button></form><div className="chat-footer"><VoiceButton lang={lang} onText={setQuestion}/><span>{hi?'हिंदी में बोलें या लिखें':'Speak or type in your language'}</span></div><Safety/></section>
}
