import {useEffect,useState} from 'react';
import {CloudRain,CloudSun,Droplets,Wind,Bookmark} from 'lucide-react';
import {api} from './api';
import {DistrictSelect,Busy,Notice,Field} from './components';
import {crops,type Language} from './i18n';
export function Weather({lang,district,setDistrict}:{lang:Language;district:string;setDistrict:(s:string)=>void}){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;setData(null);setError('');api('weather?district='+encodeURIComponent(district)).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[district]);
 return <><DistrictSelect value={district} onChange={setDistrict} lang={lang}/><Notice>{data&&!data.is_sample?'Open-Meteo API मौसम डेटा · सिंचाई से पहले स्थानीय स्थिति जाँचें।':'नमूना मौसम डेटा · Sample data, not a live forecast. खेती के फैसलों के लिए वास्तविक मौसम जाँचें।'}</Notice>{error?<p className="error">{error}</p>:!data?<Busy/>:<><section className="weather-current"><div><span className="eyebrow">{data.is_sample?'नमूना · SAMPLE CONDITIONS':'API · CURRENT CONDITIONS'}</span><h2>{district}</h2><div className="temperature">{data.temperature}°<CloudSun size={86}/></div><p>{data.is_sample?'Sample conditions':'API weather observations'}</p></div><div className="weather-stats"><div><CloudRain/> बारिश की संभावना <strong>{data.rain_probability}%</strong></div><div><Droplets/> नमी <strong>{data.humidity}%</strong></div><div><Wind/> हवा <strong>{data.wind_kmh} km/h</strong></div></div></section><h3>अगले 5 दिन · {data.is_sample?'नमूना पूर्वानुमान':'API पूर्वानुमान'}</h3><div className="forecast">{data.forecast.map((d:any)=><div className="panel" key={d.date}><span>{new Date(d.date).toLocaleDateString(lang==='hi'?'hi-IN':'en-IN',{weekday:'short',day:'numeric',month:'short'})}</span><CloudSun size={35}/><strong>{d.temperature}°C</strong><span><Droplets size={14}/>{d.rain_probability}%</span></div>)}</div><section className="panel weather-advice"><h3>🌱 किसान के लिए मौसम की बात</h3><p>{data.advisory}</p></section><p className="source">स्रोत: {data.source} · अपडेट: {new Date(data.updated_at).toLocaleString()}</p></>}</>
}
export function Market({lang,district,setDistrict}:{lang:Language;district:string;setDistrict:(s:string)=>void}){
 const [crop,setCrop]=useState('Wheat');const [market,setMarket]=useState('');const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [saved,setSaved]=useState(false);
 const query=`crop=${encodeURIComponent(crop)}&district=${encodeURIComponent(district)}&market=${encodeURIComponent(market)}`;
 useEffect(()=>{let active=true;setData(null);setSaved(false);api('market-prices?'+query).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[query]);
 async function save(){try{await api('market-prices?'+query,{method:'POST'});setSaved(true)}catch(e){setError((e as Error).message)}}
 return <><div className="panel filter-row"><Field label="फसल / Crop"><select value={crop} onChange={e=>setCrop(e.target.value)}>{crops.map(([en,hi])=><option key={en} value={en}>{lang==='hi'?hi:en}</option>)}</select></Field><Field label="ज़िला / District"><DistrictSelect lang={lang} value={district} onChange={setDistrict}/></Field><Field label="मंडी / Market"><select value={market} onChange={e=>setMarket(e.target.value)}><option value="">ज़िला मंडी</option><option value={district+' Mandi'}>{district} Mandi (sample)</option></select></Field></div><Notice>Current market price data is unavailable. वर्तमान मंडी भाव उपलब्ध नहीं हैं। नीचे केवल development sample data है।</Notice>{error?<p className="error">{error}</p>:!data?<Busy/>:<div className="panel"><div className="section-title"><h3>मंडी भाव <span className="badge amber">नमूना</span></h3><button className="secondary" onClick={save} disabled={saved}><Bookmark size={17}/>{saved?'सहेजा गया':'भाव सहेजें'}</button></div><div className="table-wrap"><table><thead><tr><th>फसल</th><th>मंडी</th><th>न्यूनतम</th><th>अधिकतम</th><th>मॉडल भाव</th><th>तारीख</th></tr></thead><tbody>{data.prices.map((p:any)=><tr key={p.commodity}><td>{crops.find(c=>c[0]===p.commodity)?.[lang==='hi'?1:0]}</td><td>{p.market}</td><td>₹{p.minimum.toLocaleString('en-IN')}</td><td>₹{p.maximum.toLocaleString('en-IN')}</td><td className="price">₹{p.modal.toLocaleString('en-IN')}</td><td>{p.date}</td></tr>)}</tbody></table></div><p className="source">इकाई: ₹ / क्विंटल · स्रोत: {data.prices[0].source}<br/>अंतिम अपडेट: {new Date(data.prices[0].updated_at).toLocaleString()}</p><p>बिक्री से पहले मंडी में वर्तमान कीमत, गुणवत्ता और शुल्क की पुष्टि करें।</p></div>}</>
}
