import {useEffect,useState} from 'react';
import {Camera,Upload,Leaf} from 'lucide-react';
import {api,post} from './api';
import {crops,type Language} from './i18n';
import {Field,Notice,Safety} from './components';
export default function Doctor({lang}:{lang:Language}){
 const [file,setFile]=useState<File|null>(null);const [url,setUrl]=useState('');const [crop,setCrop]=useState('Wheat');const [description,setDescription]=useState('');const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [sent,setSent]=useState(false);const hi=lang==='hi';
 useEffect(()=>{if(!file){setUrl('');return}const value=URL.createObjectURL(file);setUrl(value);return()=>URL.revokeObjectURL(value)},[file]);
 function select(f:File|null){setResult(null);setSent(false);if(f&&f.size>5*1024*1024){setError('तस्वीर 5 MB से छोटी होनी चाहिए।');return}setError('');setFile(f)}
 async function submit(e:React.FormEvent){e.preventDefault();if(!file)return;setBusy(true);setError('');const data=new FormData();data.append('image',file);data.append('crop',crop);data.append('description',description);try{setResult(await api('crop-diagnosis',{method:'POST',body:data}));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function escalate(){try{await post('expert-cases',{question:`${crop}: ${description||'फसल की तस्वीर की जाँच करें'}`,diagnosis_id:result.id,ai_suggestion:result.possible_issue});setSent(true)}catch(e){setError((e as Error).message)}}
 return <div className="two-columns"><section className="panel"><h3>{hi?'अपनी फसल की तस्वीर जोड़ें':'Add a photo of your crop'}</h3><p>{hi?'प्राकृतिक रोशनी में प्रभावित हिस्से की साफ़ तस्वीर लें।':'Take a clear photo of the affected part in natural light.'}</p><form onSubmit={submit}><div className="upload-box">{url?<img src={url} alt="Selected crop"/>:<><Leaf size={42}/><h3>{hi?'फसल को करीब से दिखाएँ':'Show your crop up close'}</h3><p>JPG, PNG, WEBP · अधिकतम 5 MB</p></>}<div className="upload-actions"><label className="primary"><Upload size={18}/>{hi?'तस्वीर चुनें':'Upload photo'}<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>select(e.target.files?.[0]||null)}/></label><label className="secondary"><Camera size={18}/>{hi?'फोटो लें':'Take photo'}<input type="file" accept="image/*" capture="environment" hidden onChange={e=>select(e.target.files?.[0]||null)}/></label></div></div><Field label={hi?'फसल':'Crop'}><select value={crop} onChange={e=>setCrop(e.target.value)}>{crops.map(([en,h])=><option key={en} value={en}>{hi?h:en}</option>)}</select></Field><Field label={hi?'क्या समस्या दिख रही है?':'Describe the problem'}><textarea maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="पत्तियाँ पीली हैं, धब्बे हैं…"/></Field>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={!file||busy}>{busy?'जाँच जारी है…':hi?'तस्वीर की जाँच करें':'Analyze photo'}</button></form></section><section className="panel"><Notice>{hi?'Demo vision: असली रोग पहचान मॉडल अभी जुड़ा नहीं है।':'Demo vision: no real disease detection model configured.'}</Notice>{result?<><span className="eyebrow">POSSIBLE ISSUE · संभावित समस्या</span><h2>{result.possible_issue}</h2><span className="badge amber">विश्वास: कम · Low confidence</span><h3>क्या देखें</h3>{result.symptoms.map((s:string)=><p key={s}>{s}</p>)}<h3>अगले कदम</h3><ol>{result.next_steps.map((s:string)=><li key={s}>{s}</li>)}</ol><button className="primary" disabled={sent} onClick={escalate}>{sent?'विशेषज्ञ को भेज दिया गया':'कृषि विशेषज्ञ को भेजें'}</button></>:<div className="empty"><Camera size={45}/><h3>{hi?'जाँच यहाँ दिखाई देगी':'Your analysis appears here'}</h3><p>{hi?'तस्वीर से बीमारी की 100% पुष्टि नहीं की जा सकती।':'An image diagnosis can never be 100% certain.'}</p></div>}<Safety/></section></div>
}
