import {useEffect,useState} from 'react';
import {api,post} from './api';
import {Field,Notice} from './components';
import {type Language} from './i18n';
export default function Expert({lang,staff}:{lang:Language;staff:boolean}){
 const [question,setQuestion]=useState('');const [cases,setCases]=useState<any[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [response,setResponse]=useState<Record<number,string>>({});const [image,setImage]=useState('');const [message,setMessage]=useState('');
 async function load(){try{setCases(await api('expert-cases'))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load();return()=>{if(image)URL.revokeObjectURL(image)}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await post('expert-cases',{question});setQuestion('');setMessage('आपका सवाल सहेजा गया है।');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function resolve(id:number){setBusy(true);try{await post(`expert-cases/${id}/respond`,{text:response[id],resolved:true});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function showImage(id:number){try{const token=sessionStorage.getItem('agri-token');const r=await fetch(`/api/crop-diagnosis/${id}/image`,{headers:{Authorization:`Token ${token}`}});if(!r.ok)throw new Error('Image unavailable');if(image)URL.revokeObjectURL(image);setImage(URL.createObjectURL(await r.blob()));}catch(e){setError((e as Error).message)}}
 return <><Notice>{lang==='hi'?'यह demo expert queue है। विशेषज्ञ नेटवर्क अभी जुड़ा नहीं है; आपात स्थिति में स्थानीय KVK से संपर्क करें।':'Demo expert queue. No live expert network; contact your local KVK for urgent help.'}</Notice>{!staff&&<form className="panel" onSubmit={submit}><h3>कृषि विशेषज्ञ से पूछें</h3><Field label="अपनी फसल, समस्या और ज़िला बताएं"><textarea required maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)}/></Field><button className="primary" disabled={busy}>सवाल भेजें</button>{message&&<p className="success">{message}</p>}</form>}{error&&<p className="error">{error}</p>}<h3>{staff?'विशेषज्ञ डैशबोर्ड':'आपके विशेषज्ञ अनुरोध'}</h3>{!cases.length&&<section className="panel empty">अभी कोई अनुरोध नहीं है।</section>}{cases.map(c=><section className="panel" key={c.id}><div className="section-title"><h3>#{c.id} · {c.farmer}</h3><span className={`badge ${c.resolved?'green':'amber'}`}>{c.resolved?'हल किया गया':'जवाब की प्रतीक्षा'}</span></div><p>{c.question}</p>{c.ai_suggestion&&<blockquote>AI सुझाव: {c.ai_suggestion}</blockquote>}{c.diagnosis_id&&<button className="secondary" onClick={()=>showImage(c.diagnosis_id)}>फसल की तस्वीर देखें</button>}{c.responses.map((r:any,i:number)=><div className="answer-bubble" key={i}><strong>विशेषज्ञ का जवाब</strong><p>{r.text}</p></div>)}{staff&&!c.resolved&&<div><Field label="विशेषज्ञ का जवाब"><textarea value={response[c.id]||''} onChange={e=>setResponse({...response,[c.id]:e.target.value})}/></Field><button className="primary" disabled={busy||!response[c.id]?.trim()} onClick={()=>resolve(c.id)}>जवाब भेजें और हल करें</button></div>}</section>)}{image&&<div className="modal-backdrop" onClick={()=>{URL.revokeObjectURL(image);setImage('')}}><img className="expert-image" src={image} alt="Crop case attachment"/></div>}</>
}
