import {useEffect,useState} from 'react';
import {Leaf,MapPin,Plus,Save} from 'lucide-react';
import {api} from './api';
import {Field,Busy} from './components';
import {crops,districts,districtHi,type Language} from './i18n';
export default function Farm({lang,onUpdate}:{lang:Language;onUpdate:()=>void}){
 const [data,setData]=useState<any>(null);const [farms,setFarms]=useState<any[]>([]);const [edit,setEdit]=useState(false);const [adding,setAdding]=useState(false);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [newFarm,setNewFarm]=useState({crops:['Wheat'],size_acres:'1',irrigation:'rainfed'});const hi=lang==='hi';
 async function load(){try{const [d,f]=await Promise.all([api('farmers/me'),api('farms')]);setData(d);setFarms(f);}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{await api('farmers/me',{method:'PATCH',body:JSON.stringify(data.profile)});setEdit(false);onUpdate()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);try{setFarms(await api('farms',{method:'POST',body:JSON.stringify(newFarm)}));setAdding(false)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 if(!data)return error?<p className="error">{error}</p>:<Busy/>;
 const p=data.profile;
 return <><section className="panel profile-card"><div className="avatar">{p.name[0]}</div><div><h2>{p.name}</h2><p><MapPin size={16}/> {districtHi[p.district]} · {p.village}</p><span className="badge green">{hi?'निःशुल्क योजना':'Free plan'} · {data.subscription}</span></div><button className="secondary" onClick={()=>setEdit(!edit)}>{hi?'प्रोफ़ाइल बदलें':'Edit profile'}</button></section>{error&&<p role="alert" className="error">{error}</p>}
 {edit&&<form className="panel" onSubmit={save}><div className="form-grid">{['name','village'].map(k=><Field key={k} label={k==='name'?'नाम':'गाँव'}><input required maxLength={100} value={p[k]} onChange={e=>setData({...data,profile:{...p,[k]:e.target.value}})}/></Field>)}<Field label="ज़िला"><select value={p.district} onChange={e=>setData({...data,profile:{...p,district:e.target.value}})}>{districts.map(d=><option key={d} value={d}>{districtHi[d]}</option>)}</select></Field><Field label="भाषा"><select value={p.language} onChange={e=>setData({...data,profile:{...p,language:e.target.value}})}><option value="hi">हिंदी</option><option value="en">English</option></select></Field></div><button className="primary" disabled={saving}><Save size={17}/> सहेजें</button></form>}
 <div className="section-title"><h3>{hi?'आपके खेत और फसलें':'Your farms and crops'}</h3><button className="text-button" onClick={()=>setAdding(!adding)}><Plus size={17}/> खेत जोड़ें</button></div>
 <div className="farm-grid">{farms.map(f=><section className="panel" key={f.id}><span className="action-icon green"><Leaf size={25}/></span><h2>{f.size_acres} <small>एकड़</small></h2><p>सिंचाई: {({canal:'नहर',rainfed:'वर्षा',borewell:'नलकूप',drip:'ड्रिप',other:'अन्य'} as Record<string,string>)[f.irrigation]}</p><div className="crop-tags">{f.crops.map((c:any)=><span key={c.name}>{hi?c.name_hi:c.name}</span>)}</div><p className="source">खेत #{f.id}</p></section>)}</div>
 {adding&&<form className="panel" onSubmit={add}><h3>नया खेत जोड़ें</h3><div className="form-grid"><Field label="आकार (एकड़)"><input type="number" min="0.01" step="0.01" required value={newFarm.size_acres} onChange={e=>setNewFarm({...newFarm,size_acres:e.target.value})}/></Field><Field label="सिंचाई"><select value={newFarm.irrigation} onChange={e=>setNewFarm({...newFarm,irrigation:e.target.value})}>{[['rainfed','वर्षा'],['canal','नहर'],['borewell','नलकूप'],['drip','ड्रिप'],['other','अन्य']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field></div><Field label="फसलें"><div className="crop-checks">{crops.map(([en,h])=><label key={en}><input type="checkbox" checked={newFarm.crops.includes(en)} onChange={()=>setNewFarm({...newFarm,crops:newFarm.crops.includes(en)?newFarm.crops.filter(c=>c!==en):[...newFarm.crops,en]})}/>{h}</label>)}</div></Field><button className="primary" disabled={saving}>खेत सहेजें</button></form>}
 <div className="two-columns"><section className="panel"><h3>हाल के सवाल</h3>{data.questions.length?data.questions.map((q:any)=><div className="history-item" key={q.id}><strong>{q.question}</strong><p>{q.answer}</p></div>):<p className="empty-text">अभी कोई सवाल नहीं पूछा गया। AI से पूछें पेज से शुरू करें।</p>}</section><section className="panel"><h3>हाल की फसल जाँच</h3>{data.diagnoses.length?data.diagnoses.map((d:any)=><div className="history-item" key={d.id}><strong>{d.crop}</strong><p>{d.result.possible_issue}</p><span className="badge amber">विश्वास: कम · Demo</span></div>):<p className="empty-text">अभी कोई फसल जाँच नहीं है।</p>}<h3>मौसम अलर्ट</h3>{data.weather_alerts.length?data.weather_alerts.map((a:any,i:number)=><p key={i}>{a.text}</p>):<p className="empty-text">कोई सत्यापित मौसम अलर्ट उपलब्ध नहीं है।</p>}<h3>सहेजे गए मंडी भाव</h3>{data.saved_prices.length?data.saved_prices.map((m:any)=><p key={m.id}>{m.commodity} · {m.market} · ₹{m.modal}/क्विंटल <span className="badge amber">नमूना</span></p>):<p className="empty-text">आपने अभी कोई मंडी भाव नहीं सहेजा है।</p>}</section></div></>
}
