import {ArrowUpRight,ArrowRight,Sparkles,MessageCircle,Camera,CloudSun,ChartNoAxesCombined,Leaf,Sun,Check,Mic} from 'lucide-react';
import {DistrictSelect,Notice,VoiceButton} from './components';
import {labels,type Language} from './i18n';
export type Page='home'|'ask'|'doctor'|'weather'|'market'|'farm'|'expert'|'admin';
export default function Home({lang,district,setDistrict,go,onVoice,name}:{lang:Language;district:string;setDistrict:(s:string)=>void;go:(p:Page)=>void;onVoice:(s:string)=>void;name?:string}){
 const t=labels[lang];const hi=lang==='hi';
 const actions=[{page:'ask' as Page,icon:MessageCircle,title:t.ask,description:hi?'खेती का सवाल, आसान जवाब':'Simple answers to farming questions',color:'green'},{page:'doctor' as Page,icon:Camera,title:t.doctor,description:hi?'फसल की फोटो से सलाह लें':'Get guidance from a crop photo',color:'purple'},{page:'weather' as Page,icon:CloudSun,title:t.weather,description:hi?'मौसम जानें, खेती की योजना बनाएं':'Plan your farm around the weather',color:'blue'},{page:'market' as Page,icon:ChartNoAxesCombined,title:t.market,description:hi?'अपनी फसल के मंडी भाव देखें':'Explore prices for your crops',color:'orange'},{page:'farm' as Page,icon:Leaf,title:t.farm,description:hi?'आपका खेत, आपकी जानकारी':'Your farm, your information',color:'green'}];
 return <><div className="welcome-row"><div><p className="eyebrow">{hi?'आपकी खेती का डिजिटल साथी':'YOUR DIGITAL FARMING COMPANION'}</p><h2>{name?`${hi?'नमस्ते':'Namaste'}, ${name} 👋`:t.greeting+' 👋'}</h2></div><DistrictSelect value={district} onChange={setDistrict} lang={lang}/></div>
 <section className="hero"><div className="hero-copy"><span className="hero-tag"><Sparkles size={14}/>{hi?'हर किसान के लिए, हर कदम पर':'WITH EVERY FARMER, AT EVERY STEP'}</span><h1>{hi?<>खेती की जानकारी,<br/>अब <em>AI के साथ</em></>:<>AI Farming<br/><em>Assistant</em></>}</h1><p>{t.subtitle}<br/>{hi?'अपनी भाषा में पूछें, अपने खेत के लिए समझें।':'Ask in your language. Make sense of your farm.'}</p><button className="cream-button" onClick={()=>go('ask')}><MessageCircle size={18}/>{hi?'अपना सवाल पूछें':'Ask your question'}<ArrowRight size={18}/></button><div className="hero-proof"><span><Check size={14}/>{hi?'हिंदी में आसान सलाह':'Simple Hindi guidance'}</span><span><Check size={14}/>{hi?'आपके खेत के अनुसार':'Built around your farm'}</span></div></div>
 <div className="farm-art" aria-hidden="true"><svg viewBox="0 0 560 380"><defs><linearGradient id="sky" x2="0" y2="1"><stop stopColor="#9ecca9"/><stop offset="1" stopColor="#d5e2ae"/></linearGradient></defs><rect width="560" height="380" fill="url(#sky)"/><circle cx="409" cy="92" r="46" fill="#f1d99a"/><path d="M0 207 Q90 130 220 198T560 177V380H0" fill="#7ca878"/><path d="M0 232Q180 158 560 242V380H0" fill="#4d8459"/><path d="M0 280Q240 189 560 267V380H0" fill="#a7b85e"/><path d="M0 332Q210 235 560 292V380H0" fill="#5e894b"/><path d="M-50 400Q220 245 560 310M15 421Q246 267 600 330M140 420Q300 288 610 345" fill="none" stroke="#b6c474" strokeWidth="15"/><path d="M220 205L241 152L267 205Z" fill="#315d44"/><path d="M244 173V223" stroke="#315d44" strokeWidth="7"/><rect x="328" y="211" width="53" height="35" fill="#f1d7a0"/><path d="M318 211L355 184L390 211Z" fill="#c88954"/><rect x="346" y="224" width="13" height="22" fill="#705c3c"/><path d="M498 221V121M498 163Q450 170 452 126Q486 120 498 163M498 145Q531 150 532 110Q503 107 498 145" stroke="#2e6046" strokeWidth="6" fill="#4b8053"/><path d="M95 245v-35m0 8q-19 0-18-14q16-2 18 14m0 10q20-2 20-17q-17-1-20 17" stroke="#d6d18d" strokeWidth="4" fill="#d6d18d"/></svg><div className="art-caption"><Leaf size={17}/><div><strong>{hi?'तकनीक से जुड़े, खेती में आगे बढ़ें':'Grow with better information'}</strong><span>{hi?'उत्तर प्रदेश के किसानों के लिए':'For farmers of Uttar Pradesh'}</span></div></div></div></section>
 <div className="section-title"><h3>{hi?'आज हम आपकी कैसे मदद करें?':'How can we help today?'}</h3><span>{hi?'एक विकल्प चुनें':'Choose an option'}</span></div>
 <div className="action-grid">{actions.map(a=><button key={a.page} className="action-card" onClick={()=>go(a.page)}><span className={`action-icon ${a.color}`}><a.icon size={24}/></span><ArrowUpRight className="card-arrow" size={17}/><h3>{a.title}</h3><p>{a.description}</p></button>)}</div>
 <div className="home-bottom"><section className="voice-panel"><div className="mic-circle"><Mic size={27}/></div><div><h3>{hi?'लिखना मुश्किल है? बस बोलिए।':'Prefer speaking? Just ask.'}</h3><p>{hi?'अपना सवाल हिंदी में बोलकर पूछें।':'Ask your farming question in Hindi.'}</p></div><VoiceButton lang={lang} onText={onVoice}/></section><section className="help-panel"><span className="help-icon">☀</span><div><span className="eyebrow">{hi?'सही सलाह, सही समय पर':'GUIDANCE YOU CAN TRUST'}</span><h3>{hi?'विशेषज्ञ से भी पूछ सकते हैं':'Ask an agriculture expert'}</h3><button className="text-button" onClick={()=>go('expert')}>{hi?'कृषि विशेषज्ञ से जुड़ें':'Connect with an expert'} <ArrowRight size={16}/></button></div></section></div>
 <Notice>{hi?'यह स्थानीय MVP है। मौसम और मंडी भाव नमूना हैं; AI सलाह सामान्य जानकारी है।':'Local MVP: weather and prices are samples; AI guidance is educational.'}</Notice>
 <div className="trust-strip"><span><Leaf size={16}/>{hi?'खेती के लिए बनाया गया':'Built for farming'}</span><span><Sun size={16}/>{hi?'उत्तर प्रदेश से शुरुआत':'Starting in Uttar Pradesh'}</span><span><Check size={16}/>{hi?'आसान, आपकी भाषा में':'Simple, in your language'}</span></div></>
}
