from typing import Protocol
class LLMProvider(Protocol):
    def answer(self, question: str, context: dict) -> dict: ...
class VisionProvider(Protocol):
    def analyze(self, image: bytes, crop: str, description: str) -> dict: ...
class WeatherProvider(Protocol):
    def get(self, district: str) -> dict: ...
class MarketPriceProvider(Protocol):
    def get(self, crop: str, district: str, market: str) -> dict: ...
class SpeechToTextProvider(Protocol):
    def transcribe(self, audio: bytes, language: str) -> str: ...
class TextToSpeechProvider(Protocol):
    def synthesize(self, text: str, language: str) -> bytes: ...
