# Generated by Django 5.2.12 on 2026-10-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helpful', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.advisorymessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
