# Generated by Django 5.2.12 on 2026-10-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
        ('farmers', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('farmer', 'message'), name='unique_farmer_message_feedback'),
        ),
    ]
